### ISSUE TITLE
It does not find any files to change

### ISSUE THREAD

**Issue by nikbra** [lsoft/AdjustNamespace#5]
Hello,
I really like to use this extension but it can't find any files to change
Maybe I'm doing something wrong here.
I have a solution with 2 projects. One console project and one unit test project.
I'm just moving a model from one subfolder to another and the model itself change namespace according to the new subfolder.
But after that when i'm running the extension it does not find any files to change.
I'm I doing something wrong here ?

![image](https://user-images.githubusercontent.com/20839815/204112521-8eae6e8f-265d-44af-a082-994b8f81f910.png)

Reason for above is that I have move a model / class to a new subfolder. And the project does not compile. So I want to adjust the namespace for all parts / files that use the model. But based on the message in the picture above it looks like i have to compile the project successfully first. But that's the point with adjusting the namespaces.

**Comment by lsoft** [comment]
@nikbra hi! few points:

1. VS itself may change namespaces when you drag and drop cs files in the solution tree. but it won't fix the regressions. looks like you have exactly this situation.
2. vsix does not fix the existing compilation fails (too risky to try).
3. Vsix warns you about compilation errors, because it massively depends on Roslyn and its symbol finder. if your project has compilation errors, symbol finder may does not work as we expected so adjusting namespaces may get things worse.
4. the scope of vsix is: in solution with no compilation errors find the cs files with wrong namespaces, and then fix them and fix all regressions.
5. so, please fix your compilation errors, make sure you have wrong namespace somewhere and try again.

let me know if you will see something wrong! 👍

**Comment by lsoft** [comment]
@nikbra to have a profit from this vsix you should disable fixing namespace by VS (by Roslyn to be correct). so moving files inside the solution will not change namespaces, will not break compilation. then you will able to adjust namespaces and regressions.

**Comment by nikbra** [comment]
@lsoft , thanks for the help. Yes I found this setting so VS does not update the namespace while moving files.
Now it works like expected. I will continue to test with bigger solutions. You can close this issue now.
